services:
  - type: web
    name: selin-baby-api
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server/server.js
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DATA_DIR
        value: /data/selin
